DROP TABLE "User";

CREATE TABLE "User" (
	KEY_WORD VARCHAR(255),
	NAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	EMAIL VARCHAR(255) NOT NULL,
    CONSTRAINT PK_User PRIMARY KEY  (EMAIL),

);
CREATE INDEX User_EMAIL_IDX ON "User" (EMAIL);
